#!/usr/bin/env python

from common import get_newest

import json
import sys
import shutil
import os

# check for new versions

def check():
    request = json.load(sys.stdin)
    version = request['version']['version']
    path = request['source']['heap'] + '/'
    newest_version = get_newest(path) + 1
    versions = []
    for v in range(version, newest_version + 1):
        versions.append({ 'version' : str(v)})
    print(json.dumps(versions))

if __name__ == '__main__':
    check()

