#!/usr/bin/env python

import json
import sys
import os
from distutils.dir_util import copy_tree

# get a version of the resource

def get(destination):
    request = json.load(sys.stdin)
    version = request['version']['version']
    path = request['source']['heap'] + '/' + str(version)
    if os.path.exists(path):
        copy_tree(path, destination)
    print(json.dumps({
        'version': {'version': str(version)},
        'metadata': []
    }))


if __name__ == '__main__':
    get(sys.argv[1])
